import { createPagesFunctionHandler } from "@react-router/cloudflare";

import type { Env } from "../context";
import { getLoadContext } from "../context";

export const onRequest = createPagesFunctionHandler<Env>({
  //@ts-expect-error - the server build file is generated by `remix vite:build`
  build: () => import("../build/server/index.js"),
  getLoadContext({
    context: {
      cloudflare: { env },
    },
  }) {
    return getLoadContext(env as Env);
  },
});
